-- Apps
terminal = "kitty",
filemanager = "thunar",
files = "kitty -e yazi",
menu = "fuzzel",
logout = "wlogout",
lock = "hyprlock",
colorpicker = "hyprpicker -a",
screenshot = "hyprshot",
clipboard = "bash -c 'cliphist list | rofi -dmenu | cliphist decode | wl-copy'",
volume = "pavucontrol",
bluetooth = "blueman-manager",
network = "nm-connection-editor",
