export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export EDITOR="nano"
export VISUAL="nano"
export TERMINAL="kitty"
export BROWSER="firefox"
export PAGER="less"
export LESS="-R"
